### ISSUE TITLE
В чём смысл сдавать пустую задачу?

### ISSUE THREAD

**Issue by coursar** [radikzoom/sportmaster#1]
https://github.com/radikzoom/sportmaster/blob/9924a70fa67c305e962cf0a1cbec31d5f73ffca7/src/MainR.java#L1-L10

**Comment by radikzoom** [comment]
Извините это было тестовом

**Comment by radikzoom** [comment]
@coursar - выполнено ! 
https://github.com/radikzoom/sportmaster/blob/74f8e4aedf8cc9bb67c8b6d0506b4f9e952ac78b/src/MainR.java#L1-L12
